dataset_path: data/mini_set.jsonl

model:
  provider: "openai_like"
  name: "qwen2.5:7b-instruct"      
  api_base: "http://localhost:11434/v1"
  api_key_env: "COT_AUCTION_API_KEY"  
  price:
    input_per_1k: 0.0
    output_per_1k: 0.0

strategy:
  k_list: [1, 2, 4, 8]
  max_steps: 12
  temperature: 0.4

runtime:
  seed: 42
  save_csv: true
  save_json: true
